import Head from 'next/head';
import styles from '~/styles/components/PageIndex.module.scss';
import { SampleComponent } from '~/components/SampleComponent';
import { motion } from 'framer-motion';
import { useRouter } from 'next/router';

export const PageIndex = () => {
  const router = useRouter();
  return (
    <motion.div
      key={router.asPath}
      initial={{ opacity: 0 }} // 初期状態
      animate={{ opacity: 1 }} // マウント時
      exit={{ opacity: 0 }} // アンマウント時
      transition={{ duration: 1 }}
    >
      <Head>
        <title>Next.js Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Next.js Template</h1>
      <ul className={styles.list}>
        {[...Array(9)].map((_, i) => (
          <li className={styles.item} key={i}>
            <SampleComponent text="サンプル" />
          </li>
        ))}
      </ul>
    </motion.div>
  );
};
