import Head from 'next/head';
import styles from '~/styles/components/PageIndex.module.scss';
import { SampleComponent } from '~/components/SampleComponent';

export const PageIndex = () => {
  return (
    <div className={styles.root}>
      <Head>
        <title>Next.js Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Next.js Template</h1>
      <ul className={styles.list}>
        {[...Array(9)].map((_, i) => (
          <li className={styles.item} key={i}>
            <SampleComponent text="サンプル" />
          </li>
        ))}
      </ul>
    </div>
  );
};
